# Full reference https://github.com/foundry-rs/foundry/tree/master/config
[profile.default]
auto_detect_solc = false
bytecode_hash = "none"
fuzz = { runs = 256 }
gas_reports = ["*"]
libs = ["lib"]
optimizer = true
optimizer_runs = 10_000
out = "out"
solc = "0.8.17"
src = "src"
test = "test"

[profile.ci]
fuzz = { runs = 1_000 }
verbosity = 4

[fmt]
bracket_spacing = true
int_types = "long"
line_length = 120
multiline_func_header = "all"
number_underscore = "thousands"
quote_style = "double"
tab_width = 2
variable_override_spacing = false
wrap_comments = true

[rpc_endpoints]
# mainnet = "${RPC_URL_MAINNET}"
# arbitrum = "${RPC_URL_ARBITRUM}"
# goerli = "${RPC_URL_GOERLI}"
# celo = "${RPC_URL_CELO}"
# polygon = "https://polygon-rpc.com"
sepolia = "${RPC_URL_SEPOLIA}"


[etherscan]
# ainnet = { key = "${ETHERSCAN_KEY", url = "https://api.etherscan.io/api" }
# arbitrum = { key = "${ARBISCAN_KEY}", url = "https://api.arbiscan.io/api" }
# goerli = { key = "${ETHERSCAN_KEY}", url = "https://api-goerli.etherscan.io/api" }
# celo = { key = "${CELOSCAN_KEY}", url = "https://api.celoscan.io/api" }
# polygon = { key = "${POLYGONSCAN_KEY}", url = "https://api.polygonscan.com/api" }m
sepolia = { key = "${ETHERSCAN_KEY", url = "https://api-sepolia.etherscan.io/api" }
